name: Docker Image CI Master 

on:
  push:
    branches: [ main ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build --no-cache -f WebApi/Dockerfile . --tag ${{ secrets.DOCKERHUB_REPO }}:${{ secrets.MAJOR }}.${{ secrets.MINOR }} --tag ${{ secrets.DOCKERHUB_REPO }}:latest
      
    - 
      name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    -
      name: Push to DockerHub Versioned Tag
      run: docker push ${{ secrets.DOCKERHUB_REPO }}:${{ secrets.MAJOR }}.${{ secrets.MINOR }}
      
    -
      name: Push to DockerHub Latest Tag
      run: docker push ${{ secrets.DOCKERHUB_REPO }}:latest
     
    -
      name: Update Minor version
      uses: hmanzur/actions-set-secret@v2.0.0
      with:
        name: 'MINOR'
        value: $((${{ secrets.MINOR }}+1))
        repository: ${{ secrets.PROJECT_NAME }}
        token: ${{ secrets.REPO_ACCESS_TOKEN }}   
      
